/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calc;

import java.awt.event.KeyEvent;
import jdk.nashorn.internal.objects.NativeString;

/**
 *
 * @author Selvah
 */
public class CalcDesign extends javax.swing.JFrame {

    double firstNum, secondNum,result;
    String Operations;
    private Object math;
    public CalcDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jbtn1 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDecimal = new javax.swing.JButton();
        jbtn00 = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnSub = new javax.swing.JButton();
        jbtnDiv = new javax.swing.JButton();
        jbtnMul = new javax.swing.JButton();
        jbtnSignChanger = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();
        jbtnSin = new javax.swing.JButton();
        jbtnCos = new javax.swing.JButton();
        jbtnTan = new javax.swing.JButton();
        jbtnTanh = new javax.swing.JButton();
        jbtnCosh = new javax.swing.JButton();
        jbtnSinh = new javax.swing.JButton();
        jbtnSquared = new javax.swing.JButton();
        jbtnRoot = new javax.swing.JButton();
        jbtnCube = new javax.swing.JButton();
        jbtnCubeRoot = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnLog = new javax.swing.JButton();
        jbtnLn = new javax.swing.JButton();
        jbtnInv = new javax.swing.JButton();
        jbtnBackspace = new javax.swing.JButton();
        jbtnBin = new javax.swing.JButton();
        jbtnOct = new javax.swing.JButton();
        jbtnPow = new javax.swing.JButton();
        jbtnMod = new javax.swing.JButton();
        jbtnHex = new javax.swing.JButton();
        jbtnFactorial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(255, 153, 0));
        setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        setForeground(new java.awt.Color(204, 102, 0));
        setLocation(new java.awt.Point(450, 100));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtDisplay.setForeground(new java.awt.Color(204, 0, 204));
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.setText("0");
        jtxtDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtxtDisplay.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDisplayKeyTyped(evt);
            }
        });

        jbtn1.setBackground(new java.awt.Color(153, 0, 153));
        jbtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn1.setForeground(new java.awt.Color(255, 255, 255));
        jbtn1.setText("1");
        jbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn4.setBackground(new java.awt.Color(153, 0, 153));
        jbtn4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn4.setForeground(new java.awt.Color(255, 255, 255));
        jbtn4.setText("4");
        jbtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn7.setBackground(new java.awt.Color(153, 0, 153));
        jbtn7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn7.setForeground(new java.awt.Color(255, 255, 255));
        jbtn7.setText("7");
        jbtn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn2.setBackground(new java.awt.Color(153, 0, 153));
        jbtn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn2.setForeground(new java.awt.Color(255, 255, 255));
        jbtn2.setText("2");
        jbtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn5.setBackground(new java.awt.Color(153, 0, 153));
        jbtn5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn5.setForeground(new java.awt.Color(255, 255, 255));
        jbtn5.setText("5");
        jbtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn8.setBackground(new java.awt.Color(153, 0, 153));
        jbtn8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn8.setForeground(new java.awt.Color(255, 255, 255));
        jbtn8.setText("8");
        jbtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.setBackground(new java.awt.Color(153, 0, 153));
        jbtn9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn9.setForeground(new java.awt.Color(255, 255, 255));
        jbtn9.setText("9");
        jbtn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn3.setBackground(new java.awt.Color(153, 0, 153));
        jbtn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn3.setForeground(new java.awt.Color(255, 255, 255));
        jbtn3.setText("3");
        jbtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtn6.setBackground(new java.awt.Color(153, 0, 153));
        jbtn6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn6.setForeground(new java.awt.Color(255, 255, 255));
        jbtn6.setText("6");
        jbtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn0.setBackground(new java.awt.Color(153, 0, 153));
        jbtn0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn0.setForeground(new java.awt.Color(255, 255, 255));
        jbtn0.setText("0");
        jbtn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtnDecimal.setBackground(new java.awt.Color(153, 0, 153));
        jbtnDecimal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnDecimal.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDecimal.setText(".");
        jbtnDecimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDecimalActionPerformed(evt);
            }
        });

        jbtn00.setBackground(new java.awt.Color(153, 0, 153));
        jbtn00.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn00.setForeground(new java.awt.Color(255, 255, 255));
        jbtn00.setText("00");
        jbtn00.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn00ActionPerformed(evt);
            }
        });

        jbtnAdd.setBackground(new java.awt.Color(153, 0, 153));
        jbtnAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAdd.setText("+");
        jbtnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnSub.setBackground(new java.awt.Color(153, 0, 153));
        jbtnSub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSub.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSub.setText("-");
        jbtnSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSub.setMaximumSize(new java.awt.Dimension(45, 31));
        jbtnSub.setMinimumSize(new java.awt.Dimension(45, 31));
        jbtnSub.setPreferredSize(new java.awt.Dimension(45, 31));
        jbtnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubActionPerformed(evt);
            }
        });

        jbtnDiv.setBackground(new java.awt.Color(153, 0, 153));
        jbtnDiv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnDiv.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDiv.setText("/");
        jbtnDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDiv.setMaximumSize(new java.awt.Dimension(45, 31));
        jbtnDiv.setMinimumSize(new java.awt.Dimension(45, 31));
        jbtnDiv.setPreferredSize(new java.awt.Dimension(45, 31));
        jbtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivActionPerformed(evt);
            }
        });

        jbtnMul.setBackground(new java.awt.Color(153, 0, 153));
        jbtnMul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnMul.setForeground(new java.awt.Color(255, 255, 255));
        jbtnMul.setText("x");
        jbtnMul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMul.setMaximumSize(new java.awt.Dimension(45, 31));
        jbtnMul.setMinimumSize(new java.awt.Dimension(45, 31));
        jbtnMul.setPreferredSize(new java.awt.Dimension(45, 31));
        jbtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMulActionPerformed(evt);
            }
        });

        jbtnSignChanger.setBackground(new java.awt.Color(153, 0, 153));
        jbtnSignChanger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSignChanger.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSignChanger.setText("±");
        jbtnSignChanger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSignChanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSignChangerActionPerformed(evt);
            }
        });

        jbtnEqual.setBackground(new java.awt.Color(153, 0, 153));
        jbtnEqual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnEqual.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEqual.setText("=");
        jbtnEqual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualActionPerformed(evt);
            }
        });

        jbtnSin.setBackground(new java.awt.Color(153, 0, 153));
        jbtnSin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnSin.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSin.setText("sin");
        jbtnSin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSinActionPerformed(evt);
            }
        });

        jbtnCos.setBackground(new java.awt.Color(153, 0, 153));
        jbtnCos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnCos.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCos.setText("cos");
        jbtnCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCosActionPerformed(evt);
            }
        });

        jbtnTan.setBackground(new java.awt.Color(153, 0, 153));
        jbtnTan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnTan.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTan.setText("tan");
        jbtnTan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTanActionPerformed(evt);
            }
        });

        jbtnTanh.setBackground(new java.awt.Color(153, 0, 153));
        jbtnTanh.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtnTanh.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTanh.setText("tanh");
        jbtnTanh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnTanh.setMaximumSize(new java.awt.Dimension(57, 31));
        jbtnTanh.setMinimumSize(new java.awt.Dimension(57, 31));
        jbtnTanh.setPreferredSize(new java.awt.Dimension(57, 31));
        jbtnTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTanhActionPerformed(evt);
            }
        });

        jbtnCosh.setBackground(new java.awt.Color(153, 0, 153));
        jbtnCosh.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtnCosh.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCosh.setText("cosh");
        jbtnCosh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCosh.setMaximumSize(new java.awt.Dimension(59, 31));
        jbtnCosh.setMinimumSize(new java.awt.Dimension(59, 31));
        jbtnCosh.setPreferredSize(new java.awt.Dimension(59, 31));
        jbtnCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCoshActionPerformed(evt);
            }
        });

        jbtnSinh.setBackground(new java.awt.Color(153, 0, 153));
        jbtnSinh.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtnSinh.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSinh.setText("sinh");
        jbtnSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSinhActionPerformed(evt);
            }
        });

        jbtnSquared.setBackground(new java.awt.Color(153, 0, 153));
        jbtnSquared.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnSquared.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSquared.setText("x²");
        jbtnSquared.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSquared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSquaredActionPerformed(evt);
            }
        });

        jbtnRoot.setBackground(new java.awt.Color(153, 0, 153));
        jbtnRoot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnRoot.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRoot.setText("√");
        jbtnRoot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRootActionPerformed(evt);
            }
        });

        jbtnCube.setBackground(new java.awt.Color(153, 0, 153));
        jbtnCube.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnCube.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCube.setText("x³");
        jbtnCube.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCube.setMaximumSize(new java.awt.Dimension(51, 31));
        jbtnCube.setMinimumSize(new java.awt.Dimension(51, 31));
        jbtnCube.setPreferredSize(new java.awt.Dimension(51, 31));
        jbtnCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCubeActionPerformed(evt);
            }
        });

        jbtnCubeRoot.setBackground(new java.awt.Color(153, 0, 153));
        jbtnCubeRoot.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jbtnCubeRoot.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCubeRoot.setText("³√");
        jbtnCubeRoot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCubeRoot.setMaximumSize(new java.awt.Dimension(45, 31));
        jbtnCubeRoot.setMinimumSize(new java.awt.Dimension(45, 31));
        jbtnCubeRoot.setPreferredSize(new java.awt.Dimension(45, 31));
        jbtnCubeRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCubeRootActionPerformed(evt);
            }
        });

        jbtnClear.setBackground(new java.awt.Color(153, 0, 153));
        jbtnClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnClear.setForeground(new java.awt.Color(255, 255, 255));
        jbtnClear.setText("C");
        jbtnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnLog.setBackground(new java.awt.Color(153, 0, 153));
        jbtnLog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnLog.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLog.setText("log");
        jbtnLog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogActionPerformed(evt);
            }
        });

        jbtnLn.setBackground(new java.awt.Color(153, 0, 153));
        jbtnLn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnLn.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLn.setText("ln");
        jbtnLn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLnActionPerformed(evt);
            }
        });

        jbtnInv.setBackground(new java.awt.Color(153, 0, 153));
        jbtnInv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnInv.setForeground(new java.awt.Color(255, 255, 255));
        jbtnInv.setText("1/x");
        jbtnInv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInvActionPerformed(evt);
            }
        });

        jbtnBackspace.setBackground(new java.awt.Color(153, 0, 153));
        jbtnBackspace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnBackspace.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBackspace.setText("<—");
        jbtnBackspace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackspaceActionPerformed(evt);
            }
        });

        jbtnBin.setBackground(new java.awt.Color(153, 0, 153));
        jbtnBin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnBin.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBin.setText("Bin");
        jbtnBin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBinActionPerformed(evt);
            }
        });

        jbtnOct.setBackground(new java.awt.Color(153, 0, 153));
        jbtnOct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnOct.setForeground(new java.awt.Color(255, 255, 255));
        jbtnOct.setText("Oct");
        jbtnOct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOctActionPerformed(evt);
            }
        });

        jbtnPow.setBackground(new java.awt.Color(153, 0, 153));
        jbtnPow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnPow.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPow.setText("pow");
        jbtnPow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPowActionPerformed(evt);
            }
        });

        jbtnMod.setBackground(new java.awt.Color(153, 0, 153));
        jbtnMod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnMod.setForeground(new java.awt.Color(255, 255, 255));
        jbtnMod.setText("mod");
        jbtnMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModActionPerformed(evt);
            }
        });

        jbtnHex.setBackground(new java.awt.Color(153, 0, 153));
        jbtnHex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnHex.setForeground(new java.awt.Color(255, 255, 255));
        jbtnHex.setText("Hex");
        jbtnHex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHexActionPerformed(evt);
            }
        });

        jbtnFactorial.setBackground(new java.awt.Color(153, 0, 153));
        jbtnFactorial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnFactorial.setForeground(new java.awt.Color(255, 255, 255));
        jbtnFactorial.setText("n!");
        jbtnFactorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFactorialActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("© Selvah ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtDisplay)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnSin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnSinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbtnOct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnCos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbtnHex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnTanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnTan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jbtnCube, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jbtnSignChanger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(jbtnMul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnSquared, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jbtnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbtnDiv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnFactorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jbtnCubeRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbtnLn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnPow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jbtnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jbtnLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtn00, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jbtn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnLn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnBin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnOct, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnHex, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnSquared, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnPow, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbtnFactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnSignChanger, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(jbtnInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnCube, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnCubeRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDecimalActionPerformed
        try{
        if(!jtxtDisplay.getText().contains(".")) {
        String iNum = jtxtDisplay.getText() + jbtnDecimal.getText();
        jtxtDisplay.setText(iNum);
        }
        }
        catch( Exception e) {
            jtxtDisplay.setText("Invalid Input");
        }
    
    }//GEN-LAST:event_jbtnDecimalActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn0.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn8.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn3.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMulActionPerformed
        try {
        if (Operations == null) {
        firstNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        }
        else {
            equals();
            firstNum = result;
        }
        Operations = "*"  ;
        jtxtDisplay.setText("0");
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
        
    }//GEN-LAST:event_jbtnMulActionPerformed
    public void equals() {
        try {
        secondNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        result = secondNum;
        if( null != Operations) 
            switch (Operations) {
            case "+":
                result = firstNum + secondNum;
                break;
            case "-":
                result = firstNum - secondNum;
                break;
            case "*":
                result = firstNum * secondNum;
                break;
            case "/":
                result = firstNum / secondNum;
                break;
            case "%":
                result = firstNum % secondNum;
                break;
            case "^":
                result = Math.pow(firstNum, secondNum);
                break;
            default:
                break;
        }
        jtxtDisplay.setText(String.valueOf(result));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
        
    }
    private void jbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualActionPerformed
       try {
        equals();
       firstNum = 0;
       secondNum = 0;
       Operations = null;
       }
        catch( Exception e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnEqualActionPerformed

    private void jbtnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTanActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = Math.tan(iNum);
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnTanActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(false);
        
    }//GEN-LAST:event_formWindowActivated

    private void jbtn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn00ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn00.getText();
        jtxtDisplay.setText(iNum); 
    }//GEN-LAST:event_jbtn00ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn1.getText();
        jtxtDisplay.setText(iNum);         
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        jtxtDisplay.setText("0");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn2.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn4.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn5.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn6.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn7.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String iNum = jtxtDisplay.getText() + jbtn9.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackspaceActionPerformed
        try {
        if(jtxtDisplay.getText().length() >0) {
            String bsp = null;
            StringBuilder StrB = new StringBuilder(jtxtDisplay.getText());
            StrB.deleteCharAt(jtxtDisplay.getText().length()-1);
            bsp = StrB.toString();
            jtxtDisplay.setText(bsp);
        }
        }
        catch( Exception e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnBackspaceActionPerformed

    private void jbtnBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBinActionPerformed
        try {
        int iNum = Integer.parseInt(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay.setText(Integer.toBinaryString(iNum));//String(iNum,2));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnBinActionPerformed

    private void jbtnOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOctActionPerformed
        try {
        int iNum = Integer.parseInt(String.valueOf(jtxtDisplay.getText()));
        jtxtDisplay.setText(Integer.toOctalString(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnOctActionPerformed

    private void jbtnPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPowActionPerformed
        try {
            if ( Operations == null) {
            firstNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
                  
        }
        else {
            equals();
            firstNum = result;
        }
        Operations = "^";
        jtxtDisplay.setText("0");
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnPowActionPerformed

    private void jbtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModActionPerformed
        try {
        if ( Operations == null) {
            firstNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
                  
        }
        else {
            equals();
            firstNum = result;
        }
        Operations = "%";
        jtxtDisplay.setText("0");
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnModActionPerformed

    private void jbtnHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHexActionPerformed
        try {
        int iNum = Integer.parseInt(String.valueOf(jtxtDisplay.getText()));
        String hex = (Integer.toString(iNum,16));
        jtxtDisplay.setText(NativeString.toUpperCase(hex));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnHexActionPerformed

    private void jbtnSignChangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSignChangerActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = iNum * (-1);
        jtxtDisplay.setText(String.valueOf(iNum));        
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnSignChangerActionPerformed

    private void jbtnInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInvActionPerformed
            try {
            double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
            iNum = 1/iNum;
            jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnInvActionPerformed

    private void jbtnRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRootActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = Math.sqrt(iNum);
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnRootActionPerformed

    private void jbtnSquaredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSquaredActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum= iNum * iNum ;
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnSquaredActionPerformed

    private void jbtnCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCubeActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = iNum * iNum * iNum;
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnCubeActionPerformed

    private void jbtnCubeRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCubeRootActionPerformed
        try {
        double iNum  = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = Math.cbrt(iNum);
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnCubeRootActionPerformed

    private void jbtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = Math.log10(iNum);
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnLogActionPerformed

    private void jbtnLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLnActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = Math.log(iNum);
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnLnActionPerformed

    private void jbtnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSinActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = Math.sin(iNum);
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
            
    }//GEN-LAST:event_jbtnSinActionPerformed

    private void jbtnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFactorialActionPerformed
        try {
        int iNum = Integer.parseInt(String.valueOf(jtxtDisplay.getText()));
        double fact=1;
        for(;iNum>0;iNum--) 
            fact *= iNum;
        jtxtDisplay.setText(String.valueOf(fact));
        }
        catch(NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
            
        }
        
    }//GEN-LAST:event_jbtnFactorialActionPerformed

    private void jtxtDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDisplayKeyTyped
        char c = evt.getKeyChar();
        if ( !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
     
    }//GEN-LAST:event_jtxtDisplayKeyTyped

    private void jbtnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubActionPerformed
        try {
        if ( Operations == null) {
            firstNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
                  
        }
        else {
            equals();
            firstNum = result;
        }
        Operations = "-";
        jtxtDisplay.setText("0");
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnSubActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try {
        if ( Operations == null) {
            firstNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        }
        else {
            equals();
            firstNum = result;
        }
        Operations = "+";
        jtxtDisplay.setText("0");
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivActionPerformed
        try {
        if ( Operations == null) {
            firstNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
                  
        }
        else {
            equals();
            firstNum = result;
        }
        Operations = "/";
        jtxtDisplay.setText("0");
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnDivActionPerformed

    private void jbtnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCosActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = Math.cos(iNum);
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnCosActionPerformed

    private void jbtnSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSinhActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = Math.sinh(iNum);
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnSinhActionPerformed

    private void jbtnCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCoshActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = Math.cosh(iNum);
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnCoshActionPerformed

    private void jbtnTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTanhActionPerformed
        try {
        double iNum = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        iNum = Math.tanh(iNum);
        jtxtDisplay.setText(String.valueOf(iNum));
        }
        catch( NumberFormatException e) {
            jtxtDisplay.setText("Invalid Input");
        }
    }//GEN-LAST:event_jbtnTanhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn00;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnBackspace;
    private javax.swing.JButton jbtnBin;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnCos;
    private javax.swing.JButton jbtnCosh;
    private javax.swing.JButton jbtnCube;
    private javax.swing.JButton jbtnCubeRoot;
    private javax.swing.JButton jbtnDecimal;
    private javax.swing.JButton jbtnDiv;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnFactorial;
    private javax.swing.JButton jbtnHex;
    private javax.swing.JButton jbtnInv;
    private javax.swing.JButton jbtnLn;
    private javax.swing.JButton jbtnLog;
    private javax.swing.JButton jbtnMod;
    private javax.swing.JButton jbtnMul;
    private javax.swing.JButton jbtnOct;
    private javax.swing.JButton jbtnPow;
    private javax.swing.JButton jbtnRoot;
    private javax.swing.JButton jbtnSignChanger;
    private javax.swing.JButton jbtnSin;
    private javax.swing.JButton jbtnSinh;
    private javax.swing.JButton jbtnSquared;
    private javax.swing.JButton jbtnSub;
    private javax.swing.JButton jbtnTan;
    private javax.swing.JButton jbtnTanh;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
